CREATE TABLE HOKHAU
(
	MaHK VARCHAR(15),
	DiaChi NVARCHAR(100),
	CCCDChuHo VARCHAR(15),
	PRIMARY KEY (MaHK),
);
CREATE TABLE CONGDAN
(
	CCCD VARCHAR(15) NOT NULL,
	Ten NVARCHAR(30) NOT NULL,
	NgheNghiep NVARCHAR(30),
	SDT VARCHAR(12),
	TonGiao NVARCHAR(30),
	MaHK VARCHAR(15),
	QuanHeVoiChuHo NVARCHAR(30),
	PRIMARY KEY (CCCD),
	FOREIGN KEY (MaHK) REFERENCES HOKHAU(MaHK)
);
CREATE TABLE CCCD
(
	MaCCCD VARCHAR(15),
	DacDiem NVARCHAR(50) UNIQUE NOT NULL,
	NgayCap DATE NOT NULL,
	FOREIGN KEY (MaCCCD) REFERENCES CONGDAN(CCCD),
	PRIMARY KEY (MaCCCD)
);
CREATE TABLE TAMTRUTAMVANG
(
	MaTTTV VARCHAR(15),
	CCCD VARCHAR(15),
	DiaChi NVARCHAR(100),
	NgayBD DATE,
	NgayKT DATE,
	TrangThai NVARCHAR(50),
	LiDo NVARCHAR(100) ,
	PRIMARY KEY (MaTTTV),
	FOREIGN KEY (CCCD) REFERENCES CCCD(MaCCCD)
);
CREATE TABLE KHAISINH
(
	MaKS  VARCHAR(15),
	Ten NVARCHAR (30) NOT NULL,
	NgaySinh DATE NOT NULL,
	NgayDangKy DATE NOT NULL,
	GioiTinh CHAR(1) NOT NULL,
	DanToc NVARCHAR(20) NOT NULL,
	QuocTich NVARCHAR(20) NOT NULL,
	NoiSinh NVARCHAR(100),
	CCCDCha VARCHAR(15),
	TenCha VARCHAR(30),
	CCCDMe VARCHAR(15),
	TenMe VARCHAR(30),
	FOREIGN KEY (MaKS) REFERENCES CCCD(MaCCCD),
	PRIMARY KEY (MaKS),
);
CREATE TABLE THUE
(
	MaThue VARCHAR(15),
	CCCD VARCHAR(15),
	SoTienCanNop VARCHAR(20),
	SoTienDaNop VARCHAR(30),
	NgayCap DATE,
	HanNop DATE,
	PRIMARY KEY (MaThue),
	FOREIGN KEY (CCCD) REFERENCES CCCD(MaCCCD)
);
CREATE TABLE HONNHAN
(
	MaHonNhan VARCHAR(15),
	CCCDNam VARCHAR(15),
	TenNam NVARCHAR(30),
	CCCDNu VARCHAR(15),
	TenNu VARCHAR(15),
	NoiDangKy NVARCHAR(100),
	NgayDangKy DATE,
	PRIMARY KEY (MaHonNhan),
	FOREIGN KEY (CCCDNam) REFERENCES CCCD(MaCCCD),
	FOREIGN KEY (CCCDNu) REFERENCES CCCD(MaCCCD)
);